name: Update CO2 trends

on:
  push:
  schedule:
     - cron:  '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      id: build
      run: |
        docker build --tag update_co2_trends .
        
    - name: Run docker to update notebooks
      id: run1
      run: |
        docker run --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp update_co2_trends python run_notebooks.py 
        ls

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update 09_global_trends_CO2.ipynb